codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%

comment:
  layout: "reach,diff,flags,components"
  behavior: default
  require_changes: true

component_management:
  default_rules:
    statuses:
      - type: patch
        target: 80%
  individual_components:
    - component_id: docs-theme
      name: "docs-theme"
      paths:
        - packages/docs-theme/**
