import type { HolocronConfig } from "@theholocron/cli";
import { defineConfig } from "@theholocron/cli";

export default defineConfig({
	description: "Themes and design tokens.",
	homepage: "https://docs.theholocron.dev/themes/",
	org: "theholocron",
	domain: "theholocron.dev",
	docs: { build: "workflow", https: true },
	repo: {
		protection: "strict",
		properties: {
			lifecycle: "active",
			open_source: true,
			runtime_environment: "node",
			uses_external_packages: true,
		},
		teams: [{ slug: "gatekeepers", permission: "maintain" }],
		topics: ["astro", "docs", "starlight", "theme", "typescript"],
	},
	tasks: [
		{ name: "sourceQuality.staticAnalysis", required: true },
		{ name: "sourceQuality.formatting", required: true },
		{ name: "sourceQuality.structuredDataValidation", required: true },
		{ name: "security.secretDetection", required: true },
		{ name: "platform.commitStandards", required: true },
		{ name: "verification.unitTests", required: true },
		"security.codeScanning",
		"review",
		"stale",
		"greetings",
		"dependencies",
		"bookkeeping",
		{ name: "verification.typeSafety", required: true },
		{ name: "knowledge.docs", with: { preview: true } },
		"knowledge.wiki",
	],
	extraRequiredChecks: ["codecov/patch", "codecov/project", "codecov/patch/docs-theme"],
	providers: {
		source: "github",
		ci: "github",
		issues: ["github", { labels: { inProgress: "status:in-progress", inReview: "status:in-review" } }],
		secrets: "github",
		dns: "cloudflare",
		deployment: ["cloudflare", { accountId: "9c558af98664d13fc89b7e0a0d93d5a8" }],
		workers: ["cloudflare", { accountId: "9c558af98664d13fc89b7e0a0d93d5a8" }],
		wiki: ["fern", { domain: "wiki.theholocron.dev", fernOrg: "holocron", icon: "fa-duotone fa-palette" }],
	},
	agent: "claude",
	skills: ["git-safety", "pr-workflow", "commit-standards", "security-review", "turborepo"],
} satisfies HolocronConfig);
