packages:
  - 'docs'
  - 'packages/*'

# Shared dep versions used across packages.
catalog:
  '@astrojs/starlight': ^0.41.7
  '@theholocron/astro-config': ^7.18.2
  '@theholocron/commitlint-config': ^7.15.0
  '@theholocron/eslint-config': ^7.15.0
  '@theholocron/lint-staged-config': ^7.15.0
  '@theholocron/prettier-config': ^7.15.0
  '@theholocron/semantic-release-config': ^7.15.0
  '@theholocron/stylelint-config': ^7.15.0
  '@theholocron/tsconfig': ^7.15.0
  '@theholocron/tsdown-config': ^7.15.0
  '@theholocron/vitest-config': ^7.15.0
  '@types/node': ^26.2.0
  '@vitest/coverage-v8': ^4.1.10
  '@vitest/eslint-plugin': ^1.6.26
  eslint: ^10.8.1
  eslint-plugin-n: ^18.3.0
  eslint-plugin-simple-import-sort: ^14.0.0
  astro: ^7.2.0
  globals: ^17.9.0
  tsdown: ^0.22.13
  typescript: ^5.9.3
  vitest: ^4.1.10

catalogs:
  holocron:
    '@theholocron/cli': ^3.17.0
    '@theholocron/holocron-config': ^7.15.0
    '@theholocron/holocron-plugin-github': ^3.17.0
